version: '3.1'

# Usage:
#   docker stack deploy -c stack.yml mongo (or docker-compose -f stack.yml up)

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    links:
      - mongo
 
  mongo-gui-docker:
    image: openkbs/mongo-gui-docker
    command: /usr/bin/mongodb-compass
    container_name: mongo-gui-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace
    depends_on:
      - mongo
    links:
      - mongo

#volumes:
#  mongodb_data:
#    driver: local      

