version: '3.1'

# Usage:
#   docker stack deploy -c stack.yml mongo (or docker-compose -f stack.yml up)

services:

  mongo:
    image: mongo:latest
    # setting MongoDB to use a smaller default file size
    command: --smallfiles
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./mongodb-persistence:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - mongo
    links:
      - mongo
 
